#!/usr/bin/env bash
# A non-app project must be able to prune domains it does not use (delete the
# domain doc + its pointer + its drift-map rule) and still pass validation.
set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
install="$repo_root/scripts/install-rules.sh"
validate="$repo_root/scripts/validate-installed-project.sh"

pass=0; fail=0; fails=()
check() { if [[ "$1" -eq 0 ]]; then pass=$((pass+1)); else fail=$((fail+1)); fails+=("$2"); fi; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
proj="$work/cli"
mkdir -p "$proj"
( cd "$proj" && git init -q && git config user.email t@t && git config user.name t \
  && printf 'package main\n' > main.go && git add -A && git commit -qm init )

bash "$install" --target "$proj" >/dev/null 2>&1

# Baseline: structurally valid right after install.
bash "$validate" "$proj" >/dev/null 2>&1; check $? "baseline install validates"

# Prune two domains a Go CLI does not use: localization and ui-copy.
for d in localization ui-copy; do
  rm -f "$proj/.agent/domains/$d.md" "$proj/.claude/rules/$d.md"
done
# Remove their rules from drift-map.yml (and the mirrored .agents copy is regenerated by skills, not rules).
python3 - "$proj/.agent/drift-map.yml" localization ui-copy <<'PY'
import re, sys
path, *names = sys.argv[1], *sys.argv[2:]
lines = open(path, encoding="utf-8").read().splitlines(keepends=True)
out, skip = [], False
for line in lines:
    m = re.match(r"^\s*-\s+name:\s*(\S+)", line)
    if m:
        skip = m.group(1).strip().strip('"') in names
    if not skip:
        out.append(line)
open(path, "w", encoding="utf-8").write("".join(out))
PY

bash "$validate" "$proj" >/dev/null 2>&1; check $? "validates after pruning localization + ui-copy"

# A leftover dangling pointer (domain deleted but pointer kept) must FAIL.
cp "$repo_root/templates/project/.claude/rules/build-test.md" "$proj/.claude/rules/orphan.md" 2>/dev/null || true
# Make orphan reference a non-existent domain.
printf -- '---\npaths:\n  - "x/**"\n---\nSee `.agent/domains/orphan.md`.\n' > "$proj/.claude/rules/orphan.md"
bash "$validate" "$proj" >/dev/null 2>&1
[[ $? -ne 0 ]]; check $? "dangling pointer (no matching domain) must fail validation"

total=$((pass+fail))
if [[ "$fail" -eq 0 ]]; then
  echo "[OK] prune: $pass/$total passed"; exit 0
else
  echo "[FAIL] prune: $pass/$total passed"
  for f in "${fails[@]}"; do echo "    - $f"; done
  exit 1
fi
